""" This is a "compiled" version containing only those dlls and functions that are actually used by the application """

from ctypes.wintypes import *
from .types import *

advapi32 = ctypes.windll.advapi32
comctl32 = ctypes.windll.comctl32
comdlg32 = ctypes.windll.comdlg32
gdi32 = ctypes.windll.gdi32
kernel32 = ctypes.windll.kernel32
ole32 = ctypes.windll.ole32
shell32 = ctypes.windll.shell32
user32 = ctypes.windll.user32

advapi32.RegCloseKey.argtypes = (HKEY,)
advapi32.RegCloseKey.restype = LSTATUS
advapi32.RegOpenKeyW.argtypes = (HKEY, LPCWSTR, PHKEY)
advapi32.RegOpenKeyW.restype = LSTATUS
advapi32.RegQueryValueExW.argtypes = (HKEY, LPCWSTR, LPDWORD, LPDWORD, LPVOID, LPDWORD)
advapi32.RegQueryValueExW.restype = LSTATUS
comctl32.DefSubclassProc.argtypes = (HWND, UINT, WPARAM, LPARAM)
comctl32.DefSubclassProc.restype = LPARAM
comctl32.DrawInsert.argtypes = (HWND, HWND, BOOL)
comctl32.ImageList_Add.argtypes = (HANDLE, HBITMAP, HBITMAP)
comctl32.ImageList_BeginDrag.argtypes = (HANDLE, INT, INT, INT)
comctl32.ImageList_Create.argtypes = (INT, INT, UINT, INT, INT)
comctl32.ImageList_Create.restype = HANDLE
comctl32.ImageList_Draw.argtypes = (HANDLE, INT, HDC, INT, INT, UINT)
comctl32.ImageList_GetIcon.argtypes = (HANDLE, INT, UINT)
comctl32.ImageList_GetIcon.restype = HICON
comctl32.ImageList_LoadImageW.argtypes = (HINSTANCE, LPCWSTR, INT, INT, COLORREF, UINT, UINT)
comctl32.ImageList_LoadImageW.restype = HANDLE
comctl32.MakeDragList.argtypes = (HWND,)
comctl32.TaskDialog.argtypes = (HWND, HINSTANCE, LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPCWSTR, LPINT)
comdlg32.GetOpenFileNameW.argtypes = (LPVOID,)
comdlg32.GetSaveFileNameW.argtypes = (LPVOID,)
gdi32.BitBlt.argtypes = (HDC, INT, INT, INT, INT, HDC, INT, INT, DWORD)
gdi32.CreateCompatibleBitmap.argtypes = (HDC, INT, INT)
gdi32.CreateCompatibleBitmap.restype = HBITMAP
gdi32.CreateCompatibleDC.argtypes = (HDC,)
gdi32.CreateCompatibleDC.restype = HDC
gdi32.CreateDIBSection.argtypes = (HDC, LPVOID, UINT, LPVOID, HANDLE, DWORD)
gdi32.CreateDIBSection.restype = HBITMAP
gdi32.CreateFontW.argtypes = (INT, INT, INT, INT, INT, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPCWSTR)
gdi32.CreateFontW.restype = HFONT
gdi32.CreateSolidBrush.argtypes = (COLORREF,)
gdi32.CreateSolidBrush.restype = HBRUSH
gdi32.DeleteDC.argtypes = (HDC,)
gdi32.DeleteObject.argtypes = (HANDLE,)
gdi32.ExtTextOutW.argtypes = (HDC, INT, INT, UINT, LPRECT, LPCWSTR, UINT, LPINT)
gdi32.GetDeviceCaps.argtypes = (HDC, INT)
gdi32.GetDIBits.argtypes = (HDC, HBITMAP, UINT, UINT, LPVOID, LPVOID, UINT)
gdi32.GetDIBits.restype = INT
gdi32.GetStockObject.restype = HANDLE
gdi32.GetTextMetricsW.argtypes = (HDC, LPVOID)
gdi32.MaskBlt.argtypes = (HDC, INT, INT, INT, INT, HDC, INT, INT, HBITMAP, INT, INT, DWORD)
gdi32.RoundRect.argtypes = (HDC, INT, INT, INT, INT, INT, INT)
gdi32.SelectObject.argtypes = (HDC, HANDLE)
gdi32.SelectObject.restype = HANDLE
gdi32.SetBkColor.argtypes = (HDC, COLORREF)
gdi32.SetBkMode.argtypes = (HDC, INT)
gdi32.SetDCBrushColor.argtypes = (HDC, COLORREF)
gdi32.SetDIBits.argtypes = (HDC, HBITMAP, UINT, UINT, LPVOID, LPVOID, UINT)
gdi32.SetTextColor.argtypes = (HDC, COLORREF)
gdi32.StretchDIBits.argtypes = (HDC, INT, INT, INT, INT, INT, INT, INT, INT, LPVOID, LPVOID, UINT, DWORD)
kernel32.CloseHandle.argtypes = (HANDLE,)
kernel32.CreateEventW.argtypes = (INT, BOOL, BOOL, LPCWSTR)
kernel32.CreateEventW.restype = HANDLE
kernel32.GetModuleHandleW.argtypes = (LPCWSTR,)
kernel32.GetModuleHandleW.restype = HMODULE
kernel32.GlobalAlloc.argtypes = (UINT, DWORD)
kernel32.GlobalAlloc.restype = HGLOBAL
kernel32.GlobalLock.argtypes = (HGLOBAL,)
kernel32.GlobalLock.restype = LPVOID
kernel32.GlobalUnlock.argtypes = (HANDLE,)
kernel32.LoadLibraryW.restype = HANDLE
kernel32.OpenProcess.argtypes = (DWORD, BOOL, DWORD)
kernel32.OpenProcess.restype = HANDLE
kernel32.QueryFullProcessImageNameW.argtypes = (HANDLE, DWORD, LPWSTR, LPDWORD)
kernel32.SetEvent.argtypes = (HANDLE,)
ole32.CoWaitForMultipleHandles.argtypes = (DWORD, DWORD, ULONG, LPHANDLE, LPDWORD)
shell32.DragFinish.argtypes = (WPARAM,)
shell32.DragQueryFileW.argtypes = (WPARAM, UINT, LPWSTR, UINT)
shell32.ShellExecuteW.argtypes = (HWND, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, INT)
shell32.ShellExecuteW.restype = HINSTANCE
user32.AppendMenuW.argtypes = (HWND, UINT, UINT_PTR, LPCWSTR)
user32.CallNextHookEx.argtypes = (HANDLE, INT, WPARAM, LPARAM)
user32.CallNextHookEx.restype = LPARAM
user32.CheckMenuItem.argtypes = (HMENU, UINT, UINT)
user32.CopyImage.argtypes = (HANDLE, UINT, INT, INT, UINT)
user32.CopyImage.restype = HANDLE
user32.CreateWindowExW.argtypes = (DWORD, LPCWSTR, LPCWSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID)
user32.DefWindowProcW.argtypes = (HWND, UINT, WPARAM, LPARAM)
user32.DeleteMenu.argtypes = (HMENU, UINT, UINT)
user32.DestroyWindow.argtypes = (HWND,)
user32.DialogBoxParamW.argtypes = (HINSTANCE, LPCWSTR, HWND, DLGPROC, LPARAM)
user32.DialogBoxParamW.restype = INT_PTR
user32.DispatchMessageW.argtypes = (LPMSG,)
user32.DrawIconEx.argtypes = (HDC, INT, INT, HICON, INT, INT, UINT, HBRUSH, UINT)
user32.DrawTextW.argtypes = (HANDLE, LPCWSTR, INT, LPRECT, UINT)
user32.FillRect.argtypes = (HANDLE, LPRECT, HBRUSH)
user32.FindWindowExW.argtypes = (HWND, HWND, LPCWSTR, LPCWSTR)
user32.FindWindowExW.restype = HWND
user32.FrameRect.argtypes = (HDC, LPRECT, HBRUSH)
user32.GetAsyncKeyState.restype = SHORT
user32.GetClassNameW.argtypes = (HWND, LPWSTR, INT)
user32.GetClientRect.argtypes = (HWND, LPRECT)
user32.GetClipboardData.restype = HANDLE
user32.GetCursorPos.argtypes = (LPPOINT,)
user32.GetDC.argtypes = (HWND,)
user32.GetDC.restype = HDC
user32.GetDesktopWindow.restype = HWND
user32.GetDlgItem.argtypes = (HWND, INT)
user32.GetDlgItem.restype = HWND
user32.GetFocus.restype = HWND
user32.GetIconInfo.argtypes = (HANDLE, LPVOID)
user32.GetKeyState.restype = SHORT
user32.GetMenuBarInfo.argtypes = (HWND, LONG, LONG, LPVOID)
user32.GetMenuItemInfoW.argtypes = (HMENU, UINT, BOOL, LPVOID)
user32.GetMessageW.argtypes = (LPMSG,HWND,UINT,UINT)
user32.GetParent.argtypes = (HWND,)
user32.GetParent.restype = HWND
user32.GetWindowDC.argtypes = (HWND,)
user32.GetWindowDC.restype = HDC
user32.GetWindowLongPtrA.argtypes = (HWND, LONG_PTR)
user32.GetWindowLongPtrA.restype = ULONG
user32.GetWindowLongW.argtypes = (HWND, INT)
user32.GetWindowLongW.restype = LONG
user32.GetWindowRect.argtypes = (HWND, LPRECT)
user32.GetWindowTextW.argtypes = (HWND, LPWSTR, INT)
user32.InvalidateRect.argtypes = (HWND, LPRECT, BOOL)
user32.InvertRect.argtypes = (HDC, LPRECT)
user32.IsWindowVisible.argtypes = (HWND,)
user32.LoadAcceleratorsW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadAcceleratorsW.restype = HACCEL
user32.LoadBitmapW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadBitmapW.restype = HBITMAP
user32.LoadCursorW.argtypes = (HINSTANCE, LPVOID)
user32.LoadIconW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadIconW.restype = HICON
user32.LoadImageW.argtypes = (HINSTANCE, LPCWSTR, UINT, INT, INT, UINT)
user32.LoadImageW.restype = HANDLE
user32.LoadMenuW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadMenuW.restype = HMENU
user32.MapWindowPoints.argtypes = (HWND, HWND, LPVOID, UINT)
user32.MessageBoxW.argtypes = (HWND, LPCWSTR, LPCWSTR, UINT)
user32.OffsetRect.argtypes = (LPRECT, INT, INT)
user32.OpenClipboard.argtypes = (HWND,)
user32.OpenClipboard.restype = BOOL
user32.PostMessageW.argtypes = (HWND, UINT, LPVOID, LPVOID)
user32.PostMessageW.restype = LONG_PTR
user32.RegisterWindowMessageW.argtypes = (LPCWSTR,)
user32.RegisterWindowMessageW.restype = UINT
user32.ReleaseDC.argtypes = (HWND, HANDLE)
user32.SendMessageW.argtypes = (HWND, UINT, LPVOID, LPVOID)
user32.SendMessageW.restype = LONG_PTR
user32.SetCapture.argtypes = (HWND,)
user32.SetClassLongPtrW.argtypes = (HWND, INT, LONG_PTR)
user32.SetClipboardData.argtypes = (UINT, HANDLE)
user32.SetClipboardData.argtypes = (UINT, HANDLE)
user32.SetClipboardData.restype = HANDLE
user32.SetClipboardData.restype = HANDLE
user32.SetLayeredWindowAttributes.argtypes = (HWND, COLORREF, BYTE, DWORD)
user32.SetMenu.argtypes = (HWND, HMENU)
user32.SetParent.argtypes = (HWND, HWND)
user32.SetWindowLongPtrA.argtypes = (HWND, LONG_PTR, ULONG)
user32.SetWindowLongPtrA.restype = LONG
user32.SetWindowLongPtrW.argtypes = (HWND, LONG_PTR, WNDPROC)
user32.SetWindowLongPtrW.restype = WNDPROC
user32.SetWindowPos.argtypes = (HWND, LONG_PTR, INT, INT, INT, INT, UINT)
user32.SetWindowsHookExW.argtypes = (INT, LPVOID, HINSTANCE, DWORD)
user32.SetWindowsHookExW.restype = HANDLE
user32.TrackPopupMenuEx.argtypes = (HANDLE, UINT, INT, INT, HANDLE, LPVOID)
user32.TranslateAcceleratorW.argtypes = (HWND, HACCEL, LPMSG)
user32.TranslateMessage.argtypes = (LPMSG,)
user32.UnhookWindowsHookEx.argtypes = (LPVOID,)
user32.UnhookWindowsHookEx.restype = LPARAM
