from ctypes.wintypes import *

import sys
IS_64_BIT = sys.maxsize > 2**32

LONG_PTR = ctypes.c_longlong if IS_64_BIT else ctypes.c_long
ULONG_PTR = ctypes.c_uint64 if IS_64_BIT else ctypes.c_ulong
DWORD_PTR = ULONG_PTR
INT_PTR = ctypes.c_int64 if IS_64_BIT else ctypes.c_int
UINT_PTR = WPARAM
LRESULT = LPARAM

LSTATUS = LONG
PHKEY = ctypes.POINTER(HKEY)

DLGPROC = ctypes.WINFUNCTYPE(INT_PTR, HWND, UINT, WPARAM, LPARAM)
DLGHOOKPROC = ctypes.WINFUNCTYPE(UINT_PTR, HWND, UINT, WPARAM, LPARAM)

ENUMRESNAMEPROCW = ctypes.CFUNCTYPE(BOOL, HMODULE, LPCWSTR, LPWSTR, LONG_PTR)

HOOKPROC = ctypes.WINFUNCTYPE(LRESULT, INT, WPARAM, LPARAM)

SUBCLASSPROC = ctypes.WINFUNCTYPE(LPARAM, HWND, UINT, WPARAM, LPARAM, UINT_PTR, DWORD_PTR)
WINEVENTPROCTYPE = ctypes.WINFUNCTYPE(None, HANDLE, DWORD, HWND, LONG, LONG, DWORD, DWORD)
WINHOOKPROC = ctypes.WINFUNCTYPE(LPARAM, INT, WPARAM, LPARAM)
WNDENUMPROC = ctypes.WINFUNCTYPE(BOOL, HWND, LPARAM)
WNDPROC = ctypes.WINFUNCTYPE(LONG_PTR, HWND, UINT, WPARAM, LPARAM)
